// 'use client';
import './globals.css'
import { Fira_Code } from 'next/font/google'
import { Theme } from '@radix-ui/themes'
import Navbar from './components/Navbar'
import { AuthContextProvider } from './context/AuthContext';

const firaCode = Fira_Code({ subsets: ["latin"] })

export const metadata = {
  title: 'Home Page | Intrinsically Motivating Courses',
  description: 'Generated by create next app',
  icons: {
    icon: "/icon.ico",
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={firaCode.className}>
        <AuthContextProvider>
          <Theme>
            <Navbar/>
            {children}
          </Theme>
        </AuthContextProvider>
      </body>
    </html>
  )
}
