import './globals.css'
import { Fira_Code } from 'next/font/google'
import { Theme } from '@radix-ui/themes'

const firaCode = Fira_Code({ subsets: ["latin"] })

export const metadata = {
  title: 'Intrinsically Motivating Courses',
  description: 'Generated by create next app',
  icons: {
    icon: "/icon.ico",
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={firaCode.className}>
        <Theme>
          {children}
        </Theme>
      </body>
    </html>
  )
}
