import Link from "next/link";

export const metadata = {
  title: "Intrinsically Motivating Courses",
  description: "Generated by create next app",
};

export default function Home() {
  
  return (
    <div className="flex text-2xl shadow">
      <p>This will be the about page. There will be a sign up and log in option in this page along with the necessary information about our site.</p>      
    </div>   
  )
}
